name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Amazon EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu  
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd dishari
          git sparse-checkout set backend
          git pull origin main
          cd backend
          npm i
          pm2 restart src/main.js
